using AdventOfCode2024.Day08;
using Xunit.Abstractions;

namespace AdventOfCode2024.Tests;

public class Day08Tests(ITestOutputHelper output)
{
    [Fact]
    public void Part01_Sample_Test()
    {
        // Arrange
        var result = 0;
        const string input = """
                             ............
                             ........0...
                             .....0......
                             .......0....
                             ....0.......
                             ......A.....
                             ............
                             ............
                             ........A...
                             .........A..
                             ............
                             ............
                             """;

        // Act
        var consoleOutput = ConsoleOutputHelper.CaptureOutput(() =>
        {
            result = Puzzle.Part01(input.Split(Environment.NewLine));
        });

        output.WriteLine(consoleOutput);
        
        // Assert
        result.Should().Be(14);
    }
    
    [Fact]
    public void Part01_Sample_Test2()
    {
        // Arrange
        var result = 0;
        const string input = """
                             ............
                             ............
                             ............
                             ............
                             ............
                             ............
                             ............
                             .......0....
                             ........A...
                             .........A..
                             ............
                             ............
                             """;

        // Act
        var consoleOutput = ConsoleOutputHelper.CaptureOutput(() =>
        {
            result = Puzzle.Part01(input.Split(Environment.NewLine));
        });

        output.WriteLine(consoleOutput);
        
        // Assert
        result.Should().Be(2);
    }
    
    [Fact(Skip = "WIP")]
    public void Part02_Sample_Test()
    {
        const string input = """
                             ............
                             ........0...
                             .....0......
                             .......0....
                             ....0.......
                             ......A.....
                             ............
                             ............
                             ........A...
                             .........A..
                             ............
                             ............
                             """;
        
        var result = Puzzle.Part02(input.Split(Environment.NewLine));
    
        result.Should().Be(11387);
    }
}